### PR TITLE
Add .gitignore and simplify setup

### PR DESCRIPTION
**Pull request by darth-veitcher**
Added a `.gitignore` file, changed the `ip` command so that it also works on MacOS and simplified client cert generation code in the scripts.

### CODE REVIEW

**Comment by darth-veitcher** [comment]
Just to note, having slept on it, the new `ip` command I’ve put in the script detects the *external* address as opposed to the *internal* one. Not sure what the intention was of the script as I’m still working through and debugging setup.

**Review by mr-bolle — COMMENTED** [review]
Hi, thank you for you adjustment. With this HostIP i need only the local IP from the eth0 Port, and not a external IP. This is only necessarry for the Pihole Admin Backend, the external IP is usually every 24 hour differened (if you don't have a static IP from your Internet Provider)

@darth-veitcher Is the command `ifconfig` on MacOS available? please try this command.

```
echo `ifconfig  eth0 | grep 'inet ' | awk '{print \$2}' | cut -d / -f 1`
```

*Alternative:*

`hostname -I | awk '{print $1}'`

**Comment by darth-veitcher** [comment]
OK that makes sense. I think the problem is that we're assuming a certain interface name - I've got multiple interfaces on the Mac for instance and none of them are `eth0` and so an `ifconfig` fails.

```
echo `ifconfig  eth0 | grep 'inet ' | awk '{print \$2}' | cut -d / -f 1`
...
ifconfig: interface eth0 does not exist
```

I get the following with the `hostname` option:

```
hostname -I | awk '{print $1}'
...
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
```

Possibly one where we decide to allow someone to set an environment variable and pull that if it exists/is defined?

**Comment by mr-bolle** [comment]
Please try following commands, and post the results. This IP is not really necessary for a working container. If this commands don't work, i will skip this for MacOS

`ifconfig | grep "inet " | grep -v 127.0.0.1` `ifconfig en0`

**Comment by darth-veitcher** [comment]
This seems to give me the right answer

`ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{ print $2 }'`

**Comment by mr-bolle** [comment]
> This seems to give me the right answer
> `ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{ print $2 }'`

this responce i get, i need only `192.168.178.29`. Do you get also several IP return, or only one?
> 172.26.0.1
> 192.168.64.1
> 172.24.0.1
> 172.110.1.1
> 172.18.0.1
> 172.28.0.1
> 172.17.0.1
> 172.20.0.1
> 192.168.178.29

**Comment by mr-bolle** [comment]
This seems to give me the right answer
    ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{ print $2 }'

this responce i get, i need only 192.168.178.29. Do you get also several IP return, or only one?

    172.26.0.1
    192.168.64.1
    172.24.0.1
    172.110.1.1
    172.18.0.1
    172.28.0.1
    172.17.0.1
    172.20.0.1
    192.168.178.29

***Update:*** please try `ipconfig getifaddr en0` othervise i remove this HostIP :)

**Comment by mr-bolle** [comment]
please try `ipconfig getifaddr en0` othervise i remove this HostIP :)

**Comment by darth-veitcher** [comment]
> ```
> This seems to give me the right answer
> ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{ print $2 }'
> ```
> 
> 
> this responce i get, i need only 192.168.178.29. Do you get also several IP return, or only one?
> 
> 
> ```
> 172.26.0.1
> 192.168.64.1
> 172.24.0.1
> 172.110.1.1
> 172.18.0.1
> 172.28.0.1
> 172.17.0.1
> 172.20.0.1
> 192.168.178.29
> ```
> 
> 
> _**Update:**_ please try `ipconfig getifaddr en0` othervise i remove this HostIP :)

Works fine for me now 👍

**Comment by mr-bolle** [comment]
@darth-veitcher please try the dev branch, if this changes works with your MacOS Host

**Pull request merged**
